name: build

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - '*.md'
  pull_request:
    paths-ignore:
      - '*.md'

jobs:
  unix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout LuauVM repository
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Download luau
        run: |
          wget https://github.com/Roblox/luau/releases/download/0.537/luau-ubuntu.zip
          unzip luau-ubuntu.zip
          chmod +x luau
      - name: Make tests
        run: |
          python MakeTests/main.py -t
      - name: Run tests
        run: |
          python MakeTests/run.py -r

